version: '3.8'

services:
  frontend:
    build:
      context: ./exam-vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./exam-api
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/yf_exam_lite
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Coujie123?
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Coujie123?
      MYSQL_DATABASE: yf_exam_lite
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data: